baseline: Guitar Instructor
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Guitar Instructor. Hourly guitar lessons available.
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Learn hot to play any song on the 🎸
baseurl: /
canonicalurl: true
